fix: updated version and added fix
contentstack/datasync-content-store-mongodb pull request #7
Opened 2022-11-09 15:38 UTC by abhinav-from-contentstack

removed deprecated options for mongoclient

2022-11-09 16:35 UTC, vkalta approved these changes

2022-11-10 09:12 UTC, netrajpatel requested changes

2022-11-10 09:12 UTC, netrajpatel commented on src/config.ts
> +      // autoReconnect: true,
@abhinav-from-contentstack remove commented code

2022-11-10 09:12 UTC, netrajpatel commented on src/config.ts
> +      // reconnectInterval: 1000,
@abhinav-from-contentstack Remove commented code

2022-11-10 09:30 UTC, abhinav-from-contentstack commented on src/config.ts
> +      // autoReconnect: true,
done

2022-11-10 13:52 UTC, aravindbuilt approved these changes

2022-11-10 14:21 UTC, netrajpatel approved these changes

2022-11-10 14:22 UTC, merged